-- CreateEnum
CREATE TYPE "CategoryType" AS ENUM ('TOIMISTOKULUT', 'MATKAKULUT', 'EDUSTUSKULUT', 'ATERIA', 'MARKKINOINTI_JA_MAINONTA', 'KALUSTO_JA_LAITTEET', 'PALKKAKULUT_JA_PALKKIOT', 'VUOKRA', 'VAKUUTUKSET', 'PUHELIN_JA_TIETOLIIKENNE', 'OHJELMISTOT_JA_LISENSSIT', 'KOULUTUS_JA_KURSSIT', 'KIRJANPITO_JA_LAKIPALVELUT', 'PANKKIKULUT', 'AJONEUVOKULUT', 'KOTITOIMISTON_KULUT', 'YKSITYISOTOT', 'MUUT_KULUT', 'MYYNTI_TUOTTEET', 'MYYNTI_PALVELUT', 'MUUT_TULOT');

-- AlterTable
ALTER TABLE "Receipt" ADD COLUMN     "category_id" TEXT,
ADD COLUMN     "is_deductible" BOOLEAN NOT NULL DEFAULT true;

-- CreateTable
CREATE TABLE "Category" (
    "id" TEXT NOT NULL,
    "type" "CategoryType" NOT NULL,
    "label" TEXT NOT NULL,

    CONSTRAINT "Category_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Category_type_key" ON "Category"("type");

-- AddForeignKey
ALTER TABLE "Receipt" ADD CONSTRAINT "Receipt_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE;
