POST http://localhost:5001/api/user/push-token/test
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjIzYjM5NmEwLWJmMDItNDdiMi1hYTZlLWQyNWUwNDExZTUyYyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3N5cGttdXVleHVvb2lvemRqaHNwLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhN2Q4ZjljZS1iNzk5LTQ0MmQtYWVlZS1jY2UwZjNkY2U1ZjUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NjA5MTkxLCJpYXQiOjE3ODY2MDU1OTEsImVtYWlsIjoibnV1dHRpLm55eXNzb25lbkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjYwNTU5MX1dLCJzZXNzaW9uX2lkIjoiZmY2YzUyOTMtZTkxOC00ZWI4LTliOWMtNDY3Njk5NWNhMmI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.u5UTlZ9U14wJhxEfneUkXV6FgINPl6IMhBscNus9acio7gtTQ0L-IOQTohIN-RgknOreolYEio78hF7xMIIcKg