GET http://localhost:5001/api/receipt
Cookie: token=eyJhbGciOiJFUzI1NiIsImtpZCI6IjIzYjM5NmEwLWJmMDItNDdiMi1hYTZlLWQyNWUwNDExZTUyYyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3N5cGttdXVleHVvb2lvemRqaHNwLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyMzYxMWNjYy00ODUxLTQ1YTMtODlhMy1hMTU2NTYzOTQ5MGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgwNDY3ODA5LCJpYXQiOjE3ODA0NjQyMDksImVtYWlsIjoibnV1dHRpLm55eXNzb25lbkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MDQ2NDIwOX1dLCJzZXNzaW9uX2lkIjoiZTgyNGY0ZDEtMmFkYi00MWEwLTk0NmYtYjRmNTc3YWY4ODcyIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.7vtSH3Sd9DXU1BH5pLY4QCM8fVBr6Eo06T5cxJVoCe8AGtAUXZKbBzY3tuOYhh-_XCoZE9Jc-qS1C0iRF6VfsA