GET http://localhost:5001/api/receipt
Cookie: token=eyJhbGciOiJFUzI1NiIsImtpZCI6IjIzYjM5NmEwLWJmMDItNDdiMi1hYTZlLWQyNWUwNDExZTUyYyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3N5cGttdXVleHVvb2lvemRqaHNwLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyMzYxMWNjYy00ODUxLTQ1YTMtODlhMy1hMTU2NTYzOTQ5MGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgwNDI0Njc2LCJpYXQiOjE3ODA0MjEwNzYsImVtYWlsIjoibnV1dHRpLm55eXNzb25lbkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MDQyMTA3Nn1dLCJzZXNzaW9uX2lkIjoiNDMwMjJmYjEtZmQ4ZC00MDQ3LThiNGYtMzFkMzVkMmRlOWUxIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.aqx4sqOYQTQ4S29qopyCufC_jFGkJ5lHIGtdBiU0xCITeaOHgF2xtG9KdcMI74uLdKmGRx5_SLz4AvQ_6IrJfA