POST http://localhost:5001/api/report
Cookie: token=eyJhbGciOiJFUzI1NiIsImtpZCI6IjIzYjM5NmEwLWJmMDItNDdiMi1hYTZlLWQyNWUwNDExZTUyYyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3N5cGttdXVleHVvb2lvemRqaHNwLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2NTNjNzhiMy0xYjYyLTRjMzgtODE3Mi1jYWVkZDk0YjBkYTAiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgxMDAzMDM3LCJpYXQiOjE3ODA5OTk0MzcsImVtYWlsIjoibnV1dHRpLm55eXNzb25lbkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MDk5OTQzN31dLCJzZXNzaW9uX2lkIjoiYzlmZGM1MjEtOTZlMi00YjkwLWJjNmQtODI5OTJlYjYzNGEyIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.z97o2o9J21wUO_A6PZl-C-jGhLBVZ8WrUAuCJzQPLXFNrTpCBOn64JqS7KCvS9Oj1uJyL3nTHJzHPum9VM-1CA
Content-Type: application/json

{
    "timePeriod": "Q2"
}