POST http://localhost:5001/api/report
Cookie: token=eyJhbGciOiJFUzI1NiIsImtpZCI6IjIzYjM5NmEwLWJmMDItNDdiMi1hYTZlLWQyNWUwNDExZTUyYyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3N5cGttdXVleHVvb2lvemRqaHNwLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2NTNjNzhiMy0xYjYyLTRjMzgtODE3Mi1jYWVkZDk0YjBkYTAiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgxMDAwNDA2LCJpYXQiOjE3ODA5OTY4MDYsImVtYWlsIjoibnV1dHRpLm55eXNzb25lbkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MDk5NjgwNn1dLCJzZXNzaW9uX2lkIjoiMzdiNjg3NDMtNGY1MS00NjA3LTg5OTUtY2JkMzM3ODYyY2E2IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.MyhwRN4NCCErc3GuZuczz9C6doAJZ84c0nAgD5Lgmr9o4P9tUDACyKDG9Owv-w1uiAFgo_iTbmy4DNZJB9qfag
Content-Type: application/json

{
    "timePeriod": "yearly"
}