POST http://localhost:5001/api/report
Cookie: token=eyJhbGciOiJFUzI1NiIsImtpZCI6IjIzYjM5NmEwLWJmMDItNDdiMi1hYTZlLWQyNWUwNDExZTUyYyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3N5cGttdXVleHVvb2lvemRqaHNwLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlOTgzOTNhMi1lZjc0LTRiNzYtOGE0Yy1iODg4NGZmODAxYmUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgxMjU5OTE1LCJpYXQiOjE3ODEyNTYzMTUsImVtYWlsIjoibnV1dHRpLm55eXNzb25lbkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MTI1NjMxNX1dLCJzZXNzaW9uX2lkIjoiYjBkMTMxMTQtZmI0Yi00MDkwLWE4N2MtNGE5M2JkYTIzMmRhIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.0Pl18wCrCnN5z7Ga813wzgAhskrVPvlHpAIiJs6ngrYQ3hEEmzVEY0nU4dHgFiWGkVfsEQ3uKcoPMRbo99GGcQ
Content-Type: application/json

{
    "timePeriod": "Q2"
}