POST http://localhost:5001/api/subscription/create-checkout-session
Cookie: token=eyJhbGciOiJFUzI1NiIsImtpZCI6IjIzYjM5NmEwLWJmMDItNDdiMi1hYTZlLWQyNWUwNDExZTUyYyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3N5cGttdXVleHVvb2lvemRqaHNwLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlOTgzOTNhMi1lZjc0LTRiNzYtOGE0Yy1iODg4NGZmODAxYmUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgyMTk1NzM4LCJpYXQiOjE3ODIxOTIxMzgsImVtYWlsIjoibnV1dHRpLm55eXNzb25lbkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MjE5MjEzOH1dLCJzZXNzaW9uX2lkIjoiNmNkYmU4ZGYtYmJmMy00MWQ0LThiYmMtYjhlYjJlODIyODBlIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.4-ihCLfkVFj5VJUIxQaTMDolgNIArVEVuEkdCGkqNr2smU73QF4Ls_3wjsGO3uLdwAzoz36VMLBkF70sSzM3nA
Content-Type: application/json

{
    "subscriptionType": "BASIC"
}