PUT http://localhost:5001/api/subscription/revoke-plan
Cookie: token=eyJhbGciOiJFUzI1NiIsImtpZCI6IjIzYjM5NmEwLWJmMDItNDdiMi1hYTZlLWQyNWUwNDExZTUyYyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3N5cGttdXVleHVvb2lvemRqaHNwLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlOTgzOTNhMi1lZjc0LTRiNzYtOGE0Yy1iODg4NGZmODAxYmUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgyMjAyMDQxLCJpYXQiOjE3ODIxOTg0NDEsImVtYWlsIjoibnV1dHRpLm55eXNzb25lbkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MjE5ODQ0MX1dLCJzZXNzaW9uX2lkIjoiMjI5ZGM4NGYtNWMwNS00MGVlLTlmMGEtMTc2YzU0NGExMWUzIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.vyXidHtcB_UOcrlxv4_SsWU0rv6MEP19qhDFem3lIL3gYOtOrkiWyQy8k_SWTkMYrJJywnAOj7K8TftTO_PrbA
Content-Type: application/json